import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.UnknownHostException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.mongodb.*;

@SuppressWarnings("serial")
public class Search extends javax.swing.JFrame implements ActionListener {

	/**
	 * Creates new form Search
	 */
	public Search(int caller) {
		initComponents(caller);
	}

	public Search() {
		initComponents(0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(int caller) {
		this.caller = caller;
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();

		/*
		  jLabel4.setIcon(new
		  javax.swing.ImageIcon(getClass().getResource("/images.jpg")));
		  add(jLabel4); jLabel4.setBounds(425, 10, 150, 150);
		 */
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jButton2.setBackground(new java.awt.Color(51, 0, 51));
		jButton2.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("Back");
		jButton2.setBounds(20, 20, 80, 40);
		add(jButton2);
		jButton2.addActionListener(this);

		jLabel1.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(204, 255, 204));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Search Customer");
		jLabel1.setBounds(126, 40, 314, 85);
		add(jLabel1);

		jLabel2.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(204, 255, 204));
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("Enter Field : ");
		add(jLabel2);

		jComboBox1.setFont(new java.awt.Font("SansSerif", 3, 13)); // NOI18N
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"First_Name", "Last_Name","Batch", "All_Customers"}));
		jComboBox1.addActionListener(this);

		jButton1.addActionListener(this);

		getContentPane().setBackground(new java.awt.Color(88, 0, 0));
		jLabel2.setBounds(130, 160, 130, 40);
		jComboBox1.setBounds(280, 160, 130, 40);
		add(jComboBox1);
		setTitle("Find Customers");
		setSize(600, 500);
		setLayout(null);
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Search.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Search.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Search.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Search.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new Search().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	public int caller;

	// End of variables declaration
	@Override
	public void actionPerformed(ActionEvent ae) {
		// TODO Auto-generated method stub
		add(jLabel3);
		add(jTextField1);
		add(jButton1);

		if (ae.getSource() == jComboBox1) {
			String Variable = jComboBox1.getSelectedItem().toString();
			jLabel3.setText("");
			jTextField1.setText("");
			if (Variable == "All_Customers") {
				MongoClient mongo;
				try {
					mongo = new MongoClient("localhost", 27017);
					DB db = mongo.getDB("Gym");
					DBCollection Gym_Collection = db.getCollection("Customers");
					DBCursor cursor1 = Gym_Collection.find();
					int i = 0;
					String[][] s = new String[20][11];
					while (cursor1.hasNext()) {
						cursor1.next();

						s[i][0] = cursor1.curr().get("First_Name").toString();
						s[i][1] = cursor1.curr().get("Last_Name").toString();
						s[i][3] = cursor1.curr().get("Fees").toString();
						s[i][4] = cursor1.curr().get("Age").toString();
						s[i][5] = cursor1.curr().get("Weight").toString();
						s[i][6] = cursor1.curr().get("Height").toString();
						s[i][7] = cursor1.curr().get("Phone_Number").toString();
						s[i][8] = cursor1.curr().get("Attended").toString();
						s[i][9] = cursor1.curr().get("Total").toString();
						s[i][10] = cursor1.curr().get("Address").toString();
						s[i][2]=cursor1.curr().get("Batch").toString();
						i++;
					}
					JFrame frame = new JFrame("Resulted Customers");
					frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
					Customer_Table ne = new Customer_Table(s);
					ne.setOpaque(true);
					frame.setContentPane(ne);
					frame.pack();
					frame.setVisible(true);
				} catch (UnknownHostException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
			} else {
				jLabel3.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
				jLabel3.setForeground(new java.awt.Color(204, 255, 204));
				jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
				jLabel3.setText("Enter " + Variable + ": ");
				jLabel3.setBounds(75, 230, 200, 40);

				jTextField1.setBounds(287, 230, 200, 40);

				jButton1.setBackground(new java.awt.Color(51, 0, 51));
				jButton1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
				jButton1.setForeground(new java.awt.Color(255, 255, 255));
				jButton1.setText("Search Customer");
				jButton1.setBounds(180, 300, 300, 40);
				setVisible(true);
			}
		} else if (ae.getSource() == jButton1) {

			try {

				String Variable = jComboBox1.getSelectedItem().toString();
				MongoClient mongo = new MongoClient("localhost", 27017);
				DB db = mongo.getDB("Gym");
				DBCollection Gym_Collection = db.getCollection("Customers");
				BasicDBObject fields;
				if (Variable == "First_Name" || Variable == "Last_Name" ||Variable=="Batch") {
					fields = new BasicDBObject(Variable, jTextField1.getText()
							.toString());
				} else {
					fields = new BasicDBObject(Variable,
							Integer.parseInt(jTextField1.getText().toString()));
				}
				DBCursor cursor1 = Gym_Collection.find(fields);
				int i = 0;
				String[][] s = new String[20][12];
				while (cursor1.hasNext()) {
					cursor1.next();

					s[i][0] = cursor1.curr().get("First_Name").toString();
					s[i][1] = cursor1.curr().get("Last_Name").toString();
					s[i][3] = cursor1.curr().get("Fees").toString();
					s[i][4] = cursor1.curr().get("Age").toString();
					s[i][5] = cursor1.curr().get("Weight").toString();
					s[i][6] = cursor1.curr().get("Height").toString();
					s[i][7] = cursor1.curr().get("Phone_Number").toString();
					s[i][8] = cursor1.curr().get("Attended").toString();
					s[i][9] = cursor1.curr().get("Total").toString();
					s[i][10] = cursor1.curr().get("Address").toString();
					s[i][11]=cursor1.curr().get("Sets").toString();
					s[i][2] = cursor1.curr().get("Batch").toString();
					i++;
				}
				JFrame frame = new JFrame("Resulted Customers");
				frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
				Customer_Table ne = new Customer_Table(s);
				ne.setOpaque(true);
				frame.setContentPane(ne);
				frame.pack();
				frame.setVisible(true);
			} catch (UnknownHostException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			catch (NumberFormatException e) {// To validate for data types
				JOptionPane.showMessageDialog(this,
						"Please Check the Data types");
				jTextField1.setText("");
			}
		} else if (ae.getSource() == jButton2) {
			if (caller == 1) {
				this.setVisible(false);
				new Receptionist().setVisible(true);
			}
			else {
				this.setVisible(false);
				new Admin().setVisible(true);
			}

		}
	}
}
